export { showToast } from './showToast'
export { findDuplicatesInArray } from './findDuplicatesInArray'
export { addressToCoordinates } from './addressToCoordinates'
export { FetchDataFromApiToState } from './fetchDataFromAPIToState'
export { findObjectsWithOneNotEqualValue } from './findObjectsWithOneNotEqualValue'
export { findMostSimilarObject } from './findMostSimilarObject'
export { listMostSimilarObjects } from './listMostSimilarObjects'
