export { default as ValuationFinish } from './ValuationFinish'
export { default as ValuationDetails } from './ValuationDetails'
export { default as ValuationNew } from './ValuationNew'
export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as Login } from './Login'
